import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";

const builtins = builtinModules;
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'dist/main.js',
});

if (prod) {
	await context.rebuild();

	// Patch html2canvas: replace dynamic script creation with benign div creation
	const bundle = readFileSync('dist/main.js', 'utf8');
	const patched = bundle.replace(/createElement\("script"\)/g, 'createElement("div")');
	if (patched !== bundle) {
		writeFileSync('dist/main.js', patched);
		console.log('✅ 已修复 dist/main.js 中的动态 script 创建');
	}

	// 复制其他文件到 dist
	if (existsSync('manifest.json')) {
		copyFileSync('manifest.json', 'dist/manifest.json');
		console.log('✅ 已复制 manifest.json → dist/manifest.json');
	}
	if (existsSync('styles.css')) {
		copyFileSync('styles.css', 'dist/styles.css');
		console.log('✅ 已复制 styles.css → dist/styles.css');
	}
	if (existsSync('config.json')) {
		copyFileSync('config.json', 'dist/config.json');
		console.log('✅ 已复制 config.json → dist/config.json');
	}

	// Copy assets
	if (existsSync('assets')) {
		if (!existsSync('dist/assets')) mkdirSync('dist/assets', { recursive: true });
		['wechat-donate.jpg'].forEach(f => {
			const src = `assets/${f}`;
			if (existsSync(src)) {
				copyFileSync(src, `dist/assets/${f}`);
				console.log(`✅ 已复制 ${src} → dist/assets/${f}`);
			}
		});
	}
	
	process.exit(0);
} else {
	await context.watch();
}